#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_winnfs(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(cmk.utils.paths.local_agents_dir + "/windows/plugins/winnfs.ps1",
                 plugins_dir + "/winnfs.ps1")

bakery_info["winnfs"] = {
    "bake_function" : bake_winnfs,
    "os"            : [ "windows" ],
}
